### ISSUE TITLE
Importer un composant

### ISSUE THREAD

**Issue by Johanb3k** [CreamLib/Angular_Code#13]
Salut Emmanuel.

J'ai un soucis en voulant importer un composant, que j'ai déplacé dans la librairie, dans un composant de l'application.
Dans le TS modal-page.component.ts, je modifie l'import du composant modal avec : import { ModalComponent } from 'creamnglib';
mais j'ai une erreur, le module 'creamnglib' est introuvable.
Il l'est aussi dans le fichier app.module cela dit.

Branche: mooveComponents-part3

Tu as une idée?

Merci :)

**Comment by EmmanuelDemey** [comment]
Je regarde cela de suite.

**Comment by EmmanuelDemey** [comment]
Sans faire expres, je viens de commiter sur master, désolé. 
Je pense que tu avais oublier cette ligne dans le fichier public_api.ts

**Comment by Johanb3k** [comment]
Hello Emmanuel,

Ah ok, effectivement j'avais oublié ces imports, merci :)
Par contre, tu sais pourquoi dans le fichier "app.module.ts", le module 'creamnglib' est introuvable?
import { CreamnglibModule } from 'creamnglib';

C'est peut-être lié également, mais une fois sur 2 j'ai une erreur de build : 
BUILD ERROR
EPERM: operation not permitted, unlink 'C:\wamp64\www\Git\creamNG\Angular_Code\dist\creamnglib\lib\input'
Error: EPERM: operation not permitted, unlink 'C:\wamp64\www\Git\creamNG\Angular_Code\dist\creamnglib\lib\input'

Merci

**Comment by EmmanuelDemey** [comment]
Faudrait essayer de mettre tous les imports dans le fichier public_api peut être ?
C'est sur la même branche ?

**Comment by Johanb3k** [comment]
Hello Emmanuel,

Je viens de voir que je ne t'avais pas répondu, désolé.
C'est tout bon maintenant. Je ne sais pas pourquoi mais c'était mon repo en local qui merdait.

Merci!
